- 1514080901120/app.js
- 1514080901120/app.json
- 1514080901120/app.wxss
- 1514080901120/pages/index/index.js
- 1514080901120/pages/index/index.wxml
- 1514080901120/pages/index/index.wxss
- 1514080901120/pages/logs/logs.js
- 1514080901120/pages/logs/logs.json
- 1514080901120/pages/logs/logs.wxml
- 1514080901120/pages/logs/logs.wxss
- 1514080901120/project.config.json
- 1514080901120/utils/util.js
> #1 #25 第1次实验代码

- 1514080901113/app.js
- 1514080901113/app.json
- 1514080901113/app.wxss
- 1514080901113/pages/index/index.js
- 1514080901113/pages/index/index.wxml
- 1514080901113/pages/index/index.wxss
- 1514080901113/pages/logs/logs.js
- 1514080901113/pages/logs/logs.json
- 1514080901113/pages/logs/logs.wxml
- 1514080901113/pages/logs/logs.wxss
- 1514080901113/project.config.json
- 1514080901113/utils/util.js
> #1 #33 第1次实验代码

- 1514080901128/app.js
- 1514080901128/app.json
- 1514080901128/app.wxss
- 1514080901128/pages/index/index.js
- 1514080901128/pages/index/index.wxml
- 1514080901128/pages/index/index.wxss
- 1514080901128/pages/logs/logs.js
- 1514080901128/pages/logs/logs.json
- 1514080901128/pages/logs/logs.wxml
- 1514080901128/pages/logs/logs.wxss
- 1514080901128/utils/util.js
> #1 #82 第 第一次实验代码

- 1514080901228/app.js
- 1514080901228/app.json
- 1514080901228/app.wxss
- 1514080901228/pages/index/index.js
- 1514080901228/pages/index/index.wxml
- 1514080901228/pages/index/index.wxss
- 1514080901228/pages/logs/logs.js
- 1514080901228/pages/logs/logs.json
- 1514080901228/pages/logs/logs.wxml
- 1514080901228/pages/logs/logs.wxss
- 1514080901228/project.config.json
- 1514080901228/utils/util.js
> #1 #62 第1次实验代码（改了title）

- 1514080901206/app.js
- 1514080901206/app.json
- 1514080901206/app.wxss
- 1514080901206/pages/index/index.js
- 1514080901206/pages/index/index.wxml
- 1514080901206/pages/index/index.wxss
- 1514080901206/pages/logs/logs.js
- 1514080901206/pages/logs/logs.json
- 1514080901206/pages/logs/logs.wxml
- 1514080901206/pages/logs/logs.wxss
- 1514080901206/project.config.json
- 1514080901206/utils/util.js
> #1  #150号 第1次实验代码

- 1514080901220/app.js
- 1514080901220/app.json
- 1514080901220/app.wxss
- 1514080901220/pages/index/index.js
- 1514080901220/pages/index/index.wxml
- 1514080901220/pages/index/index.wxss
- 1514080901220/pages/logs/logs.js
- 1514080901220/pages/logs/logs.json
- 1514080901220/pages/logs/logs.wxml
- 1514080901220/pages/logs/logs.wxss
- 1514080901220/utils/util.js
> #1 #52 第一次实验代码“

- 1514080901239/app.js
- 1514080901239/app.json
- 1514080901239/app.wxss
- 1514080901239/pages/index/index.js
- 1514080901239/pages/index/index.wxml
- 1514080901239/pages/index/index.wxss
- 1514080901239/pages/logs/logs.js
- 1514080901239/pages/logs/logs.json
- 1514080901239/pages/logs/logs.wxml
- 1514080901239/pages/logs/logs.wxss
- 1514080901239/project.config.json
- 1514080901239/utils/util.js
> #1 #64 第一次实验代码“

- 1514080901140/app.json
- 1514080901140/app.wxss
- 1514080901140/pages/index/index.js
- 1514080901140/pages/index/index.wxml
- 1514080901140/pages/index/index.wxss
> #2 #13 第2次实验代码

- 1513071001116/app.json
- 1513071001116/pages/index/index.js
- 1513071001116/pages/index/index.wxml
> #2 #42 第二次实验代码

- 1514080901121/app.json
- 1514080901121/app.wxss
- 1514080901121/pages/index/index.js
- 1514080901121/pages/index/index.wxml
- 1514080901121/pages/index/index.wxss
创建了一个日期选择器和三个选项。开始想直接用WEUI里的日期选择器，然而我并不想要 年份 的选择，所以修改了多项选择。
> #1 #70 第二次试验代码

- 1514080901104/experiments3/index.js
- 1514080901104/experiments3/index.wxml
> #3 #63 第3次实验代码

- 1514080901127/pages/index/index.js
- 1514080901127/pages/index/index.wxml
- 1514080901127/pages/index/index.wxss
> #3 #12 第3次实验代码

- 1514080901206/pages/index/index.wxml
> #2  #150  第2次实验代码

- 1514080901128/app.json
- 1514080901128/pages/biliview/biliview.js
- 1514080901128/pages/biliview/biliview.wxml
使用了b站的一个数据接口，这个接口对应b站的动画区以及动画区排行榜组件。本来想读取图片并显示，但是出现渲染层网络层错误，具体原因还在研究。
emmmm之前是打算直接用dalao提供的第三方api，但是dalao的服务器昨天开始无法访问= =所以直接用官方接口
> #5 #82 第5次实验代码

- 1514080901132/pages/text/text.js
- 1514080901132/pages/text/text.wxml
- 1514080901132/pages/text/text.wxss
- 1514080901132/project.config.json
> #4 #90 第4次实验代码

- 1514080901206/pages/form/form.js
- 1514080901206/pages/form/form.wxml
- 1514080901206/pages/index/index.js
- 1514080901206/pages/index/index.wxml
实现汇率转化，目前仅支持人民币转美元/英镑，接下来会逐渐完善。
> #5  #150 第5次实验代码

- 1514080901110/pages/user/user.js
> #5 #166 第五次实验代码 

- 1514080901132/pages/index/index.js
- 1514080901132/pages/index/index.wxml
- 1514080901132/project.config.json
> #5 #90 第5次实验代码

- 1514080901121/pages/index/index.js
- 1514080901121/pages/index/index.wxml
> #5 #70 第5次实验代码

- 1514080901226/form.js
> #5 #50  第5次实验代码

- 1514080901210/readme.md
> #6 #48 第6次试验

- 1514080901230/pages/index/index.wxml
> #3 #89 第三实验代码

- 1514080901128/README.md
> #6 #82 一个4次未过审的小程序
